#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2025.2.1"

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
    # "all",
     "apriltag",
     "commands2",
    # "cscore",
     "navx",
    # "pathplannerlib",
    # "phoenix5",
     "phoenix6",
    # "playingwithfusion",
    # "rev",
    # "romi",
    # "sim",
    # "xrp",
]

# Other pip packages to install
requires = [
    "photonlibpy==2025.0.0b8","lemonlib @ git+https://github.com/FRC5113/LemonLib@6b028105fb477c7cfbef1ae694786f66fb051c5f"
]
