name: Trigger Sync to LemonLib

on:
  push:
    paths:
      - 'src/lemonlib/**'

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/FRC5113/LemonLib/dispatches \
          -d '{"event_type":"sync_event"}'
